{% set name = "cyclus-build-deps" %}
{% set version = "1.5.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0
  skip: True  # [win or py<=27 or py>=37]
  detect_binary_files_with_prefix: true

requirements:
  host:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - glibmm
    - glib 2.56
    - jinja2
    - pandas
    - cython 0.26
    - coincbc <2.9.10
    - boost-cpp <1.69
    - libblas
    - libcblas
    - liblapack
    - libxmlpp
    - bzip2
    - hdf5
    - sqlite
    - pcre
    - gettext
    - xz
  run:
    - cmake
    - pkg-config
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - jinja2
    - pandas
    - glibmm
    - glib 2.56
    - libxmlpp
    - {{ pin_compatible("coincbc", max_pin="x.x.x") }}
    - libblas
    - libcblas
    - liblapack
    - {{ pin_compatible("boost-cpp", max_pin="x.x.x") }}
    - hdf5
    - sqlite
    - pcre
    - gettext
    - bzip2
    - xz
    - websockets
    - pprintpp

test:
  commands:
    - test "!" -f "${PREFIX}/lib/cyclus.so"  # [linux]
    - test -f "${PREFIX}/lib/libblas.so"  # [linux]
    - test -f "${PREFIX}/lib/liblapack.so"  # [linux]
    - test -f "${PREFIX}/lib/libhdf5.so"  # [linux]
    - test "!" -f "${PREFIX}/lib/cyclus.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libblas.dylib"  # [osx]
    - test -f "${PREFIX}/lib/liblapack.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libhdf5.dylib"  # [osx]

about:
  home: http://fuelcycle.org
  license: BSD 3-clause
  summary: 'Build dependency metapackage for Cyclus.'

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - FlanFlanagan
    - katyhuff
