{% set name = "cyclus-build-deps" %}
{% set version = "1.5.0" %}
{% set variant = "openblas" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 5
  skip: true  # [win]
  features:
    - blas_{{ variant }}

requirements:
  build:
    - python
  run:
    - python
    - cmake
    - pkg-config
    - libxmlpp
    - coincbc
    - blas 1.1 {{ variant }}
    - openblas 0.2.20|0.2.20.*
    - lapack
    - boost-cpp 1.66.*
    - hdf5 1.10.1
    - sqlite 3.13.*
    - pcre
    - gettext
    - bzip2 1.0.*
    - xz 5.2.*
    - setuptools
    - nose
    - pytables
    - pandas
    - jinja2
    - cython
    - gcc
    - websockets  # [py3k]
    - pprintpp

test:
  commands:
    - test "!" -f "${PREFIX}/lib/cyclus.so"  # [linux]
    - test -f "${PREFIX}/lib/libblas.so"  # [linux]
    - test -f "${PREFIX}/lib/liblapack.so"  # [linux]
    - test -f "${PREFIX}/lib/libhdf5.so"  # [linux]
    - test "!" -f "${PREFIX}/lib/cyclus.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libblas.dylib"  # [osx]
    - test -f "${PREFIX}/lib/liblapack.dylib"  # [osx]
    - test -f "${PREFIX}/lib/libhdf5.dylib"  # [osx]

about:
  home: http://fuelcycle.org
  license: BSD 3-clause
  summary: 'Build dependency metapackage for Cyclus.'

extra:
  recipe-maintainers:
    - scopatz
    - gonuke
    - bam241
    - FlanFlanagan
