travis:
  secure:
    BINSTAR_TOKEN: BAgwoEeuCqjyrVKkXCLmN+taIRxBqODb80VLjh1s1q68mwJpoSZGjmKaVpsDaVaTp0VrJAcoGFGS8gJ1SCfSuQTKqChw52qYTCxpe96wAUVUnkVUqTJBURq26oVV79sp42Xoj2nLS+YoSEEwVebVzEcazf0xIrbm6bcJuyK+y/z3RMVZb2zOpZEUY6cwuRs3OKRF6HuGoBlnuBu66GrYC91n5ocZTr7898qn336LAY5ioE8l1JdkwJnZ5n7GmJkgDTXphPv1Z08soX3kOPNfCuFxvcqSXngsp1albBTyi/kV3VdPYh77OTzaTYjDROyR7IfMJXzrooYjtf4tnzHaxJlDNQNXf0cQiNidCLsIwcl6jbVJYTRv+w5cmFQrO38iGHckgv4JZqvx5ICfrOhn9aLT8eCqOHDhcLINdMRXBGeScz2rE5jKEXsXU8jcW2+RbsUPfpsw4HYx/RrkRBBwtQ4by75qEQ6yhKTdHIoM/+YLnmOT44hhN2TXZ1jbPt9aTwjSgTZbJn0orTfXnbHLC0xli17qn0mTDr2Aq2guY9p/qD+1tZbQGCOL/wJvLl0vEh6MyEAl3OaeCAqURyZ/TQRPoTPWnU7xsLfT0qxu9OzI5BksSfV2SY6MYCgw2W4yfZQBdnl0aBBgWNd8n3JUxGBhsjIbPmAfP0Dlj+OxCbA=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
